config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"

  resource :session, only: [:new, :create, :destroy]
  
  
  get 'users/' => 'users#index'
  get 'users/new' => 'users#new' 
  get 'users/:id' => 'users#show', as: :user
  post 'events/attend/:id' => 'events#attend', as: :events_attend

  post 'users' => 'users#create'

  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id/' => 'users#update'

  delete 'users/:id' => 'users#destroy'

  get "/admin", to: "pages#admin"

  
  resources :users

  get 'events/' => 'events#index'
  get 'events/new' => 'events#new'
  get 'events/:id' => 'events#show', as: :event

  post 'events' => 'events#create'

  get 'events/:id/edit' => 'events#edit'
  patch 'events/:id' => 'events#update'

  delete 'events/:id' => 'events#destroy'

  
  get 'user_interests' => 'user_interests#index', as: :user_interests

  resources :events do 
    member do
       post :join
    end
  end

end

app/models/Attendee.rb
class Attendee
  include Mongoid::Document

  belongs_to :user
  belongs_to :event

  validates :event_id, :uniqueness => { :scope => :user_id }

end

app/models/UserEvent.rb
class UserEvent
	include Mongoid::Document

  belongs_to :user
  belongs_to :event
  end

app/models/UserInterest.rb
class UserInterest
	include Mongoid::Document

  belongs_to :user
  belongs_to :interest
  end

app/models/event.rb
class Event
  include Mongoid::Document

  # has_mongoid_attached_file :image 
  # validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  field :name, type: String
  field :place, type: String
  field :when, type: String
  field :price, type: Integer
  field :short_description, type: String
  field :description, type: String
  field :starter1, type: String
  field :starter2, type: String
  field :starter3, type: String
  field :entree1, type: String
  field :entree2, type: String
  field :entree3, type: String
  field :dessert1, type: String
  field :dessert2, type: String
  field :dessert3, type: String
  field :drink, type: String


  
  has_many :attendees

  # accepts_nested_attributes_for :interests
  # accepts_nested_attributes_for :users

  #has_many :users, through: :interests
  def users
    User.find(self.userinterests.map(&:shoe_id))
  end

  def user_ids
    ret = []
    self.interests.each do |r|
      ret << r.user_id if r.user_id
    end
    ret
  end

  def user_ids=(list)
    self.interests.destroy
    list.each do |user_id|
      self.interests.create(user_id: user_id)if user_id
    end
  end

  #has_many :interests, through: :users ?????

  
end

app/models/user.rb
class User
	include Mongoid::Document
	include ActiveModel::SecurePassword
	include Mongoid::Paperclip


    # FOR UPLOADING IMAGES #

    has_mongoid_attached_file :image, 
    :styles => { 
    	:medium   => ['250x250',    :jpg]
    }
    validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	# TO ESTABLISH PASSWORD? 
	has_secure_password


	# FIELDS WITIN THE MODEL
	field :first_name, type: String
	field :last_name, type: String
	field :email, type: String
	field :password_digest, type: String
	# "SPECIAL" FIELD TO ALLOW ADMIN ACCESS
	field :is_admin, type: Mongoid::Boolean, default: false

	#VALIDATES FIELDS TO BE PRESENT AND UNIQUE
	validates_presence_of :first_name
	validates_uniqueness_of :email

	# TO CREATE DATABASE RELATIONSHIP
	# has_many :attendees
    has_many :events


  # def events
  #   Event.find event_ids
  # end
  #   #accepts_nested_attributes_for :pastries

  # # def event_ids
  # #     event_ids_array = []
  # #     self.attendees.each do |one_attendee|
  # #       if one_attendee.event_id
  # #         event_ids_array.push one_attendee.event_id
  # #     end 
  # #   end
  # #     event_ids_array 
  # # end

  #   def event_ids=(list)
  #     self.attendees.destroy
  #     list.each do |event_id|
  #       self.attendees.create(event_id: event_id)
  #     end
  #   end

  #   # some way of showing a list
  #   def event_list
  #     events_string = ""
  #     events.each do |one_event|
  #       events_string += ", " + one_event.name
  #     end
  #     events_string.slice(2,events_string.length - 1)
  #     events_string
  #   end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :check_admin, only: [:new, :edit, :create, :destroy, :update]

	def index
		@events = Event.all
		@attendees = Attendee.all
	end


	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(params.require(:event).permit(:image, :name, :place, :when, :price, :short_description, :description, :starter1, :starter2, :starter3, :entree1, :entree2, :entree3, :dessert1, :dessert2, :dessert3, :drink, :eventimage ))
		if @event.save 
			redirect_to events_path
		else
			render 'new'
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(params[:product])
			redirect_to event_path(@event)
		else
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

  	def attend
	    @event = Event.find(params[:id].to_s)
	    Attendee.create(user_id: current_user.id, event_id: @event.id)
	    redirect_to events_path
  	end

  	def withdraw
	    @event = Event.find(params[:id].to_s)
	    Attendee.destroy(user_id: current_user.id, event_id: @event.id)
	    redirect_to events_path
  	end

  	def business
	    parameters = { term: params[:term], limit: 16 }
	    render json: Yelp.client.business('Los Angeles', parameters)
  	end


	private 

	def check_admin
		unless current_user && current_user.is_admin
			redirect_to events_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def admin
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		@is_login = true
	end

	def create
		u = User.where(email: params[:user][:email]).first
		# first make sure we actually find a user
		# then see if user authenticates
		if u && u.authenticate(params[:user][:password])
			# sets the cookie to the browser
			session[:user_id] = u.id.to_s
			if u.is_admin == true
				redirect_to admin_path
			else
				redirect_to events_path
			end

		else
			redirect_to new_user_path
		end
	end


	def destroy
		# Kill our cookies!
		reset_session
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		# @id = params[:id]
		# @user = User.find(@id)
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
		@is_signup = true
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			redirect_to events_path
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(params.require(:user).permit(:first_name, :last_name, :email, :image))
			redirect_to users_path
		else 
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private 

	def check_admin
		unless current_user && current_user.is_admin
			redirect_to events_path
		end
	end

	private

	def user_params
	    params.require(:user).permit(:is_admin, :image, :first_name, :last_name, :password, :password_confirmation, :email, event_ids: [])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>EDIT AN EVENT</h1>

<center>
	<div class="signupform">
		<%= form_for @event do |f| %>
		<% if @event.errors.any? %>
		<div class="error messages">
			<h2>Form is Invalid</h2>
			<ul>
				<% for message in @event.errors.full_messages %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<p>
			<%= f.label :name %><br />
			<%= f.text_field :name %>
		</p>
		<p>
			<%= f.label :place %><br />
			<%= f.text_field :place %>
		</p>
		<p>
			<%= f.label :when %><br />
			<%= f.text_field :when %>
		</p>
		<p>
			<%= f.label :price %><br />
			<%= f.text_field :price %>
		</p>
		<p>
			<%= f.label :short_description %><br />
			<%= f.text_field :short_description %>
		</p>
		<p>
			<%= f.label :description %><br />
			<%= f.text_field :description %>
		</p>
		<p>
			<%= f.label :starter1 %><br />
			<%= f.text_field :starter1 %>
		</p>
		<p>
			<%= f.label :starter2 %><br />
			<%= f.text_field :starter2 %>
		</p>
		<p>
			<%= f.label :starter3 %><br />
			<%= f.text_field :starter3 %>
		</p>
		<p>
			<%= f.label :entree1 %><br />
			<%= f.text_field :entree1 %>
		</p>
		<p>
			<%= f.label :entree2 %><br />
			<%= f.text_field :entree2 %>
		</p>
		<p>
			<%= f.label :entree3 %><br />
			<%= f.text_field :entree3 %>
		</p>
		<p>
			<%= f.label :dessert1 %><br />
			<%= f.text_field :dessert1 %>
		</p>
		<p>
			<%= f.label :dessert1 %><br />
			<%= f.text_field :dessert1 %>
		</p>
		<p>
			<%= f.label :dessert2 %><br />
			<%= f.text_field :dessert2 %>
		</p>
		<p>
			<%= f.label :dessert3 %><br />
			<%= f.text_field :dessert3 %>
		</p>
		<p>
			<%= f.label :drink %><br />
			<%= f.text_field :drink %>
		</p>
		<p class="button"><%= f.submit %></p>
		<% end %>
	</div>
	<%= link_to "Delete This Event", :event, method: :delete %>

	<br>
	<%= link_to "back to the list of events!", events_path %>

</center>

app/views/events/index.html.erb
<div class="container">
	<div class="row">
		<div class="well">
			<h1 class="text-center">Upcoming Events</h1>
			<div class="list-group">
				<% @events.each do |s| %>
				<a class="list-group-item ">
					<div class="media col-md-3">
						<figure class="pull-left">
							<img class="media-object img-rounded img-responsive"  src="http://placehold.it/300x240" alt="placehold.it/450x250" >

						</figure>
					</div>
					<div class="col-md-6">
						<h2 class="list-group-item-heading"> <%= s.name %> </h2>
						<p class="list-group-item-text"> 
							<%= s.short_description %>
						</p>
						<div class="col-md-3 text-center">
							
							
						</div>

						<!-- <div class="participants"> 
							 <p class="list-group-item-text"> --> 
								<h3>Check Out Who's Going</h3>
								<div class="participantimages">
								<% s.attendees.each do |k| %>

								<%= image_tag(User.find(k.user_id).image, size:"80x80" ) %>

								<% end %>
								
							</div>

						</div>
						<h2><%= s.when %></h2>
						<h3>$<%= s.price %>.00</h3>
						
						<%= button_to "Attend", events_attend_path(s.id), method: :post, class: "btn btn-warning btn-lg"  %>
					

						<%= button_to "More Info", event_path(s), class: "btn btn-default btn-lg", :method => :get %>
						<% if current_user.is_admin %>
						<%= button_to "Edit", edit_event_path(s), class: "btn btn-warning btn-lg", :method => :get  %>				
						<% end %>
						<% end %>
					</a>
					
				</div>
			</div>
		</div>
	</div>
</div>	

app/views/events/new.html.erb
<h1>NEW EVENT</h1>

<center>
	<div class = "newusercontainer">
	<%= form_for @event do |f| %>

	<p class="signupfield">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p class="signupfield">
		<%= f.label :place %><br />
		<%= f.text_field :place %>
	</p>
	<p class="signupfield">
		<%= f.label :when %><br />
		<%= f.text_field :when %>
	</p>
	<p class="signupfield">
		<%= f.label :price %><br />
		<%= f.text_field :price %>
	</p>
	<p class="signupfield">
		<%= f.label :short_description %><br />
		<%= f.text_field :short_description %>
	</p>
	<p class="signupfield">
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</p>
	<p class="signupfield">
		<%= f.label :starter1 %><br />
		<%= f.text_field :starter1 %>
	</p>
	<p class="signupfield">
		<%= f.label :starter2 %><br />
		<%= f.text_field :starter2 %>
	</p>
	<p class="signupfield">
		<%= f.label :starter3 %><br />
		<%= f.text_field :starter3 %>
	</p>
	<p class="signupfield">
		<%= f.label :entree1 %><br />
		<%= f.text_field :entree1 %>
	</p>
	<p class="signupfield">
		<%= f.label :entree2 %><br />
		<%= f.text_field :entree2 %>
	</p>
	<p class="signupfield">
		<%= f.label :entree3 %><br />
		<%= f.text_field :entree3 %>
	</p>
	<p class="signupfield">
		<%= f.label :dessert1 %><br />
		<%= f.text_field :dessert1 %>
	</p>
	<p class="signupfield">
		<%= f.label :dessert1 %><br />
		<%= f.text_field :dessert1 %>
	</p>
	<p class="signupfield">
		<%= f.label :dessert2 %><br />
		<%= f.text_field :dessert2 %>
	</p>
	<p class="signupfield">
		<%= f.label :dessert3 %><br />
		<%= f.text_field :dessert3 %>
	</p>
	<p class="signupfield">
		<%= f.label :drink %><br />
		<%= f.text_field :drink %>
	</p>
	<%= f.file_field :image %> <br />

	<%= f.submit %></p>
<% end %>

app/views/events/show.html.erb
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner">
			<div class="item active">
				<img src="http://foodporndaily.com/pictures/grilled-peach-salad-with-baby-greens-raspberries-and-raspberry-champagne-vinaigrette.jpg" width="100%">
			</div>
		</div>
	</div>
	<div class="container1">
		<div class="jumbotron">
			<div class="list-group">
				<div class="media col-md-12">
					<h2 class="list-group-item-heading"><center>Event Description</center> </h2>
					<p class="list-group-item-text"> 
						<%= @event.description %>
					</p>

				</div>
			</div>
		</div>				
		<div class="col-md-12 text-center">
			<h2 class="list-group-item-heading">The Details </h2>
			<p class="list-group-item-text"> 
				<h3>
					<li>Where: <%= @event.place %></li>
					<li>When: <%= @event.when %></li>
					<li>Price: $<%= @event.price %>.00</li>
				</h3>
			</p>
		</div>
		<div class="jumbotron">
			<div class="col-md-12 text-center">
				<h2 class="list-group-item-heading">The Prix Fixie Menu Included In Price</h2>
				<p class="list-group-item-text"> 
				<h3>Starters<br /></h3> (Your Choice of)
					<li><%= @event.starter1 %></li>
					<li><%= @event.starter2 %></li>
					<li><%= @event.starter3 %></li>
			
			</p>
			<p class="list-group-item-text"> 
				<h3>Entrees<br /></h3> (Your Choice of)
					<li><%= @event.entree1 %></li>
					<li><%= @event.entree2 %></li>
					<li><%= @event.entree3 %></li>
				
			</p>
			<p class="list-group-item-text"> 
				<h3>Desserts<br /></h3> (Your Choice of)
					<li><%= @event.dessert1 %></li>
					<li><%= @event.dessert2 %></li>
					<li><%= @event.dessert3 %></li>
				
			</p>
			
<center>
		<%= link_to "Attend", events_attend_path, method: :post, class: "btn btn-primary btn-lg" %>
		<%= link_to "Back To Events", events_path, class: "btn btn-default btn-lg" %>
	</center>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PUTAFACEON</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <div class="rightsidenav">
        <% if current_user %>
         <div class="logbutton">
          <%= link_to 'EVENTS', events_path  %>   
        </div>
         
          <% if current_user.is_admin %>
         <div class="logbutton">
          <%= link_to 'ADMIN PANEL', admin_path  %>   
        </div>
        <% end %>
          <div class="logbutton">
              <%= link_to 'LOG OUT', session_path, method: :delete %>
          </div>
        <% else %>
            <div class="logbutton">
              <%= link_to 'LOG IN', new_session_path  %>   
            </div>
          </div>
       
        
<% end %>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_usercontrol.html.erb
<% if current_user.is_admin %>
<%= link_to "Delete This User", :user, method: :delete, data: { confirm: "Are you sure you want to delete #{@user.first_name}?"}, class: "btn btn-default btn-lg" %>

<%= link_to "Edit this user!", edit_user_path, class: "btn btn-default btn-lg" %>
<% end %>


<%= link_to "Back to the list!", users_path, class: "btn btn-default btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Putaface</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, intial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>

</body>
</html>

app/views/pages/admin.html.erb
<h1><center>Hello, Admin! What Would You Like To Do Today?</center></h2>
	<div class="admincontainer">
		<div class="jumbotrons">
			<div class="jumbotron">

				<p>Create A New User</p>

				<%= link_to "Add A New User", new_user_path, class: "btn btn-primary btn-lg" %>
				<br/><br/>
				<%= link_to "View/Edit All Users", users_path, class: "btn btn-primary btn-lg" %>

			</div>


			<div class="jumbotron">

				<p>Create A New Event</p>

				<%= link_to "Add A New Event", new_event_path, class: "btn btn-warning btn-lg" %>
				<br/><br/>
				<%= link_to "View/Edit All Events", events_path, class: "btn btn-warning btn-lg" %>
			</div>

		</div>
	</div>

app/views/pages/home.html.erb
<!-- Warming Up -->
<link href='http://fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
<script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>

<!--Video Section-->
<section class="content-section video-section">
	<div class="pattern-overlay">
		<a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=TRr9aZ5eo9E&feature=youtu.be',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}"></a>
		<div class="homecontainer">
			<div class="row">
				<div class="col-lg-12">
					<h1>ever wonder who's<br />
						<u><span id="rotate"></span></u></p></h1> 

						<ul style="display:none">
							<li>A Republican?</li>
							<li>A PC User?</li>
							<li>A Vegan?</li>
							<li>An Android User?</li>
							<li>A Furry?</li>
							<li>A Juggalo?</li>
						</ul>
						<div class="homebutton">
						<a href="users/new"><button type="button" class="btn btn-warning btn-lg">MEET SOMEONE DIFFERENT</button></a>
					</div>
					</div>

				</div>

			</div>
		</div>

	</section>

app/views/users/edit.html.erb
<div class="container" style="padding-top: 60px;">


  <h1 class="page-header">Edit Profile</h1>
  <div class="row">
  	<%= form_for @user, html: { class: 'form' } do |f| %>
    <!-- left column -->
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center">
        <%= image_tag @user.image, size:"250x250" %>
        <h6>Upload a different photo...</h6>
        <%= f.file_field :image %> 
        <%= f.submit "Upload" %> 
      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
    	

      <h3>Edit Your Info</h3>
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <%= f.label "First Name" %><br />
          <%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %><br />
          <%= f.text_field :email, placeholder: "Email Address", class: 'form-control' %>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <span></span>
          </div>
        </div>
      </form>


      <h1> Edit this User record and Event records together</h1>


      And here is some data from the event record that can be edited:<br><br>
      <%= f.collection_check_boxes :event_ids, Event.all, :id, :name %>
      <br><br>
      <%= f.submit "Save Changes", class: "btn btn-primary" %> 
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
			<h1> User List </h1>
        <div class="span12">
    		<ul class="thumbnails">
    			<% @users.each do |s| %>
                  <div class="thumbnail clearfix">
                    <%= image_tag s.image, size:"150x150", class: "pull-left span2 clearfix" %>
                     <!-- <%= image_tag(s.image.url) %> -->
                    <div class="caption" class="pull-left">
                      <center>
                    	<h3><%= s.first_name %> <%= s.last_name %></h3>
                     <%= link_to "Show more details!", user_path(s), class: "btn btn-default btn-lg" %>
                   </center>
                    </div>
                  </div> 

                  <% end %>              
            </ul>
        </div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row form-group">
		<div class="col-xs-12">
			<ul class="nav nav-pills nav-justified thumbnail setup-panel">
				<li class="active"><a href="#step-1">
					<h4 class="list-group-item-heading">Register</h4>
					<p class="list-group-item-text">Create your user profile</p>
				</a></li>
			</ul>
		</div>
	</div>
	<div class="row-setup-content" id="step-1">
		<div class="col-xs-12">
			<div class="col-md-12 well text-center">
				<h1> REGISTER</h1>
				<div class="signupform">
					<%= form_for @user do |f| %>
					<% if @user.errors.any? %>
					<div class="error messages">
						<h2>Form is Invalid</h2>
						<ul>
							<% for message in @user.errors.full_messages %>
							<li><%= message %></li>
							<% end %>
						</ul>
					</div>
					<% end %>
					<div class="signupfields">
						<p class="signupfield">
							<%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %>
						</p>
						<p class="signupfield">
							
							<%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>
						</p>
						<p class="signupfield">
							<%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
						</p>
						<p class="signupfield">
							<%= f.password_field :password, placeholder: "Password", class: 'form-control' %>
						</p>
						<p class="signupfield">
							<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control' %>
						</p>
						 <%= f.file_field :image %> <br />
					</div>
					<%= f.submit "Create User", class: "btn btn-primary btn-lg" %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="well">
		<div class="row">
			<h1>Some More Info About <%= @user.first_name %></h1>

			<%= image_tag @user.image, size:"150x150" %>

			<div class="signupform">
				<p>This user's name is <%= @user.first_name %> <%= @user.last_name %>, and his/her email is <%= @user.email %> </p>

				<%= render 'layouts/usercontrol' %>


			</div>
		</div>
	</div>
</div>